name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository }}"

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build changelog from PRs with labels
      #   id: build_changelog
      #   uses: mikepenz/release-changelog-builder-action@v4
      #   with:
      #     configuration: ".github/changelog-configuration.json"
      #     # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
      #     # combining possible changelogs of all previous PreReleases in between.
      #     # PreReleases show a partial changelog since last PreRelease.
      #     ignorePreReleases: "${{ !contains(github.ref, '-rc') }}"
      #     outputFile: .github/release-notes.md
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     body: ${{steps.build_changelog.outputs.changelog}}
      #     prerelease: "${{ contains(github.ref, '-rc') }}"
      #     # Ensure target branch for release is "main"
      #     commit: main
      #     token: ${{ secrets.GITHUB_TOKEN }}
